import numpy as np
from assimilate import *
from model import *
from measure import *

assim_dict ={"output_folder": "../Output/EnKF",
             "input_folder": "../Input/NFS",
             "tmp_folder": "/localscratch/Users/apensoneault/EnKF",
	     "param_folder": "/nfsscratch/Users/apensoneault/EnKF",
	     "mean_filename": "mean.csv",
             "var_filename": "var.csv",
             "time_filename": "time.csv",
             "rain_file" : "south_skunk_2_rainfall.csv",
             "sensor_file" : "south_skunk_2_sensor_2.txt",
             "meas_suffix" : "_meas.csv",
             "prm_file": "south_skunk_2.prm",
             "rvr_file": "south_skunk_2.rvr",
             "sav_file": "south_skunk_2.sav",
             "gbl_file": "gbl.txt",
             "seed": 1,
             "initial_state_variables": np.array([1.0, 0.0, 0.02, 0.0]),
             "initial_percent_std": np.array([5.0, 5.0, 5.0, 5.0]),
             "percent_std": np.array([0.0, 0.0, 0.0, 0.0]),
             "baseflow_percent_std": np.array([0.0, 0, 0.05, 0.01]),
             "assimilation_algo": EnKF,
             "model_algo": Model_252_GSMA,
             "measure_algo": Linear,
             "time_start": 1396310400, 
             "time_interval": 60,
             "time_stop": 1417392000,
             "time_plot": 1396310400,
             "rainfall_percent_std":1,
             "ens_num": 3,
             "smoother_cycles":2,
             "global_param":np.array([.55, .13, -.1, .02, 2.0425e-6, .02, 0.5, .10, 0., 99.0, 3.0]),
             "init_param_est": 0*np.array([0.05, 0.02, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
             "param_est": 0*np.array([0.01, 0.01, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
             "river_name": "South Skunk River",
             "param_names":["v_0","lambda_1","lambda_2","v_h","k_3","k_I_factor","h_b","S_L","A","B","exponent"],
             "units":["m/s","units","units","m/s","1/min","units","m","m","units","units","units"],
             "plot_cycles":1,
             "parallel":False,
             "evap_file":"evap.mon",
             "evap_error":0,
             "outlet_id":272678,
             "var_list":[2],
             "var_title":["s_t"],
             "var_units":["m"],
             "state_exclude":np.array([1,2])
            }
